name: Test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    name: Linux Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [5.x, 6.x, 7.x, 8.x, 9.x, 10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test
        env:
          CI: false
